chore(ci): check version increment on CI (#39)

diff --git a/.github/workflows/helm.yml b/.github/workflows/helm.yml
--- a/.github/workflows/helm.yml
+++ b/.github/workflows/helm.yml
@@ -22,10 +22,27 @@ jobs:
         with:
           version: "v3.5.0"
         id: install
+      - name: Install tools
+        run: |
+          sudo snap install yq
       - name: Build dependencies
         run: helm dep update charts/hlf-k8s
       - name: Lint Chart
         run: helm lint charts/hlf-k8s
+      - name: Validate version increment
+        env:
+          HARBOR_AUTH_TOKEN: ${{ secrets.HARBOR_AUTH_TOKEN }}
+          HARBOR_AUTH_USER: "robot$connect-hlf-k8s+connect-hlf-k8s-pusher"
+        run: |
+          helm repo add --username=$HARBOR_AUTH_USER --password=$HARBOR_AUTH_TOKEN owkin-priv https://core.harbor.tooling.owkin.com/chartrepo/connect-hlf-k8s
+          RES=$(helm search repo owkin-priv/hlf-k8s --version $(yq eval .version charts/hlf-k8s/Chart.yaml))
+          if [ "${RES}" == "No results found" ]; then
+            echo "Version incremented"
+          else
+            echo "Validation failed, you should upgrade the chart version in Chart.yaml"
+            exit 1
+          fi
+
   publish:
     name: Publish
     runs-on: ubuntu-latest
